//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetHair_Egypt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clinic()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public string CName { get; set; }
        public string Email { get; set; }
        public string CUrl { get; set; }
        public string Password { get; set; }
        public string CImage1 { get; set; }
        public string CImage2 { get; set; }
        public string CImage3 { get; set; }
        public string CImage4 { get; set; }
        public int CID { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
    }
}
